name: Tests
on: workflow_call
jobs:
  cypress_e2e_tests:
    name: Cypress e2e
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_LOCAL_SERVICE_ROLE_KEY }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_LOCAL_ANON_KEY}}
      NEXT_PUBLIC_CYPRESS_TEST_USER: admin@example.com
      NEXT_PUBLIC_CYPRESS_TEST_PASS: admin123
      NEXT_PUBLIC_ENVIRONMENT: test
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Start local Supabase instance
        run: npx supabase start

      - name: Create users for the local Supabase instance
        run: npx ts-node supabase/tools/createUserForEachRole.ts

      - name: Create bucket for the local Supabase instance
        run: npx ts-node supabase/tools/createStorage.ts

      - name: Remove irrelevant files that may cause TypeScript errors
        run:
          rm -f ./supabase/seed/seed.ts

      - name: Compile
        run: npm run build

      - name: Run Cypress e2e tests
        run: npm run cypress:e2e

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
          retention-days: 1

      - name: Upload Videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: videos
          path: cypress/videos
          retention-days: 1

  jest_tests:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run jest tests
        run: npm run jest:all
